// Code generated by gqlkit. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-chat/sdk/builder"
	"example-go-chat/sdk/fields"
	"example-go-chat/sdk/scalars"
	"example-go-chat/sdk/types"
)

// BillingFeaturesBuilder builds a query for billingFeatures
//
// Embeds *builder.BaseBuilder for shared query-assembly + execution logic,
// and an op-kind marker (Query / Mutation) so the type only satisfies the
// matching batch.QueryBatchable / batch.MutationBatchable interface.
type BillingFeaturesBuilder struct {
	*builder.BaseBuilder
	builder.QueryMarker
}

// After sets the after argument
func (b *BillingFeaturesBuilder) After(v *scalars.Cursor) *BillingFeaturesBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *BillingFeaturesBuilder) First(v *int) *BillingFeaturesBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *BillingFeaturesBuilder) Before(v *scalars.Cursor) *BillingFeaturesBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *BillingFeaturesBuilder) Last(v *int) *BillingFeaturesBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// Select configures which fields to return
func (b *BillingFeaturesBuilder) Select(selector func(*fields.BillingFeatureConnectionFields)) *BillingFeaturesBuilder {
	selector(fields.NewBillingFeatureConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *BillingFeaturesBuilder) Execute(ctx context.Context) (types.BillingFeatureConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result types.BillingFeatureConnection `json:"billingFeatures"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return types.BillingFeatureConnection{}, err
	}

	return response.Result, nil
}
