// Code generated by gqlkit. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-chat/sdk/builder"
	"example-go-chat/sdk/fields"
	"example-go-chat/sdk/types"
)

// IAiModelBuilder builds a query for iAiModel
//
// Embeds *builder.BaseBuilder for shared query-assembly + execution logic,
// and an op-kind marker (Query / Mutation) so the type only satisfies the
// matching batch.QueryBatchable / batch.MutationBatchable interface.
type IAiModelBuilder struct {
	*builder.BaseBuilder
	builder.QueryMarker
}

// ID sets the id argument
func (b *IAiModelBuilder) ID(v string) *IAiModelBuilder {
	b.SetArg("id", v, "String!")
	return b
}

// Select configures which fields to return
func (b *IAiModelBuilder) Select(selector func(*fields.AiModelFields)) *IAiModelBuilder {
	selector(fields.NewAiModelFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *IAiModelBuilder) Execute(ctx context.Context) (types.AiModel, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result types.AiModel `json:"iAiModel"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return types.AiModel{}, err
	}

	return response.Result, nil
}
