// Code generated by gqlkit. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-chat/sdk/builder"
	"example-go-chat/sdk/fields"
	"example-go-chat/sdk/inputs"
	"example-go-chat/sdk/scalars"
	"example-go-chat/sdk/types"
)

// CworkspaceSubsBuilder builds a query for cworkspaceSubs
//
// Embeds *builder.BaseBuilder for shared query-assembly + execution logic,
// and an op-kind marker (Query / Mutation) so the type only satisfies the
// matching batch.QueryBatchable / batch.MutationBatchable interface.
type CworkspaceSubsBuilder struct {
	*builder.BaseBuilder
	builder.QueryMarker
}

// After sets the after argument
func (b *CworkspaceSubsBuilder) After(v *scalars.Cursor) *CworkspaceSubsBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *CworkspaceSubsBuilder) First(v *int) *CworkspaceSubsBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *CworkspaceSubsBuilder) Before(v *scalars.Cursor) *CworkspaceSubsBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *CworkspaceSubsBuilder) Last(v *int) *CworkspaceSubsBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// Where sets the where argument
func (b *CworkspaceSubsBuilder) Where(v *inputs.CWorkspaceSubWhereInput) *CworkspaceSubsBuilder {
	b.SetArg("where", v, "CWorkspaceSubWhereInput")
	return b
}

// Select configures which fields to return
func (b *CworkspaceSubsBuilder) Select(selector func(*fields.CWorkspaceSubConnectionFields)) *CworkspaceSubsBuilder {
	selector(fields.NewCWorkspaceSubConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *CworkspaceSubsBuilder) Execute(ctx context.Context) (types.CWorkspaceSubConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result types.CWorkspaceSubConnection `json:"cworkspaceSubs"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return types.CWorkspaceSubConnection{}, err
	}

	return response.Result, nil
}
