// Code generated by gqlkit. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-chat/sdk/builder"
	"example-go-chat/sdk/fields"
	"example-go-chat/sdk/types"
)

// ChatbotBuilder builds a query for chatbot
//
// Embeds *builder.BaseBuilder for shared query-assembly + execution logic,
// and an op-kind marker (Query / Mutation) so the type only satisfies the
// matching batch.QueryBatchable / batch.MutationBatchable interface.
type ChatbotBuilder struct {
	*builder.BaseBuilder
	builder.QueryMarker
}

// ID sets the id argument
func (b *ChatbotBuilder) ID(v string) *ChatbotBuilder {
	b.SetArg("id", v, "String!")
	return b
}

// Select configures which fields to return
func (b *ChatbotBuilder) Select(selector func(*fields.ChatbotFields)) *ChatbotBuilder {
	selector(fields.NewChatbotFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *ChatbotBuilder) Execute(ctx context.Context) (*types.Chatbot, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result *types.Chatbot `json:"chatbot"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return nil, err
	}

	return response.Result, nil
}
