// Code generated by gqlkit. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-chat/sdk/builder"
	"example-go-chat/sdk/fields"
	"example-go-chat/sdk/inputs"
	"example-go-chat/sdk/scalars"
	"example-go-chat/sdk/types"
)

// FuncToolLogsBuilder builds a query for funcToolLogs
//
// Embeds *builder.BaseBuilder for shared query-assembly + execution logic,
// and an op-kind marker (Query / Mutation) so the type only satisfies the
// matching batch.QueryBatchable / batch.MutationBatchable interface.
type FuncToolLogsBuilder struct {
	*builder.BaseBuilder
	builder.QueryMarker
}

// After sets the after argument
func (b *FuncToolLogsBuilder) After(v *scalars.Cursor) *FuncToolLogsBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *FuncToolLogsBuilder) First(v *int) *FuncToolLogsBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *FuncToolLogsBuilder) Before(v *scalars.Cursor) *FuncToolLogsBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *FuncToolLogsBuilder) Last(v *int) *FuncToolLogsBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// OrderBy sets the orderBy argument
func (b *FuncToolLogsBuilder) OrderBy(v []inputs.FuncToolLogOrder) *FuncToolLogsBuilder {
	b.SetArg("orderBy", v, "[FuncToolLogOrder!]")
	return b
}

// Where sets the where argument
func (b *FuncToolLogsBuilder) Where(v *inputs.FuncToolLogWhereInput) *FuncToolLogsBuilder {
	b.SetArg("where", v, "FuncToolLogWhereInput")
	return b
}

// Select configures which fields to return
func (b *FuncToolLogsBuilder) Select(selector func(*fields.FuncToolLogConnectionFields)) *FuncToolLogsBuilder {
	selector(fields.NewFuncToolLogConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *FuncToolLogsBuilder) Execute(ctx context.Context) (types.FuncToolLogConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result types.FuncToolLogConnection `json:"funcToolLogs"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return types.FuncToolLogConnection{}, err
	}

	return response.Result, nil
}
