// Code generated by gqlkit. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-chat/sdk/builder"
	"example-go-chat/sdk/fields"
	"example-go-chat/sdk/scalars"
	"example-go-chat/sdk/types"
)

// BillingPlansBuilder builds a query for billingPlans
//
// Embeds *builder.BaseBuilder for shared query-assembly + execution logic,
// and an op-kind marker (Query / Mutation) so the type only satisfies the
// matching batch.QueryBatchable / batch.MutationBatchable interface.
type BillingPlansBuilder struct {
	*builder.BaseBuilder
	builder.QueryMarker
}

// After sets the after argument
func (b *BillingPlansBuilder) After(v *scalars.Cursor) *BillingPlansBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *BillingPlansBuilder) First(v *int) *BillingPlansBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *BillingPlansBuilder) Before(v *scalars.Cursor) *BillingPlansBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *BillingPlansBuilder) Last(v *int) *BillingPlansBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// Select configures which fields to return
func (b *BillingPlansBuilder) Select(selector func(*fields.BillingPlanConnectionFields)) *BillingPlansBuilder {
	selector(fields.NewBillingPlanConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *BillingPlansBuilder) Execute(ctx context.Context) (types.BillingPlanConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result types.BillingPlanConnection `json:"billingPlans"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return types.BillingPlanConnection{}, err
	}

	return response.Result, nil
}
