// Code generated by gqlkit. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-chat/sdk/builder"
	"example-go-chat/sdk/fields"
	"example-go-chat/sdk/types"
)

// AvailableAppsBuilder builds a query for availableApps
//
// Embeds *builder.BaseBuilder for shared query-assembly + execution logic,
// and an op-kind marker (Query / Mutation) so the type only satisfies the
// matching batch.QueryBatchable / batch.MutationBatchable interface.
type AvailableAppsBuilder struct {
	*builder.BaseBuilder
	builder.QueryMarker
}

// Select configures which fields to return
func (b *AvailableAppsBuilder) Select(selector func(*fields.AppStoreAppFields)) *AvailableAppsBuilder {
	selector(fields.NewAppStoreAppFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *AvailableAppsBuilder) Execute(ctx context.Context) ([]types.AppStoreApp, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result []types.AppStoreApp `json:"availableApps"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return nil, err
	}

	return response.Result, nil
}
