// Code generated by gqlkit. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-chat/sdk/builder"
	"example-go-chat/sdk/fields"
	"example-go-chat/sdk/scalars"
	"example-go-chat/sdk/types"
)

// CworkspaceFeatureLimitsBuilder builds a query for cworkspaceFeatureLimits
//
// Embeds *builder.BaseBuilder for shared query-assembly + execution logic,
// and an op-kind marker (Query / Mutation) so the type only satisfies the
// matching batch.QueryBatchable / batch.MutationBatchable interface.
type CworkspaceFeatureLimitsBuilder struct {
	*builder.BaseBuilder
	builder.QueryMarker
}

// After sets the after argument
func (b *CworkspaceFeatureLimitsBuilder) After(v *scalars.Cursor) *CworkspaceFeatureLimitsBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *CworkspaceFeatureLimitsBuilder) First(v *int) *CworkspaceFeatureLimitsBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *CworkspaceFeatureLimitsBuilder) Before(v *scalars.Cursor) *CworkspaceFeatureLimitsBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *CworkspaceFeatureLimitsBuilder) Last(v *int) *CworkspaceFeatureLimitsBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// Select configures which fields to return
func (b *CworkspaceFeatureLimitsBuilder) Select(selector func(*fields.CWorkspaceFeatureLimitConnectionFields)) *CworkspaceFeatureLimitsBuilder {
	selector(fields.NewCWorkspaceFeatureLimitConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *CworkspaceFeatureLimitsBuilder) Execute(ctx context.Context) (types.CWorkspaceFeatureLimitConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result types.CWorkspaceFeatureLimitConnection `json:"cworkspaceFeatureLimits"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return types.CWorkspaceFeatureLimitConnection{}, err
	}

	return response.Result, nil
}
