// Code generated by gqlkit. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-chat/sdk/builder"
	"example-go-chat/sdk/fields"
	"example-go-chat/sdk/inputs"
	"example-go-chat/sdk/scalars"
	"example-go-chat/sdk/types"
)

// MessagesBuilder builds a query for messages
//
// Embeds *builder.BaseBuilder for shared query-assembly + execution logic,
// and an op-kind marker (Query / Mutation) so the type only satisfies the
// matching batch.QueryBatchable / batch.MutationBatchable interface.
type MessagesBuilder struct {
	*builder.BaseBuilder
	builder.QueryMarker
}

// After sets the after argument
func (b *MessagesBuilder) After(v *scalars.Cursor) *MessagesBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *MessagesBuilder) First(v *int) *MessagesBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *MessagesBuilder) Before(v *scalars.Cursor) *MessagesBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *MessagesBuilder) Last(v *int) *MessagesBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// OrderBy sets the orderBy argument
func (b *MessagesBuilder) OrderBy(v []inputs.MessageOrder) *MessagesBuilder {
	b.SetArg("orderBy", v, "[MessageOrder!]")
	return b
}

// Where sets the where argument
func (b *MessagesBuilder) Where(v *inputs.MessageWhereInput) *MessagesBuilder {
	b.SetArg("where", v, "MessageWhereInput")
	return b
}

// Select configures which fields to return
func (b *MessagesBuilder) Select(selector func(*fields.MessageConnectionFields)) *MessagesBuilder {
	selector(fields.NewMessageConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *MessagesBuilder) Execute(ctx context.Context) (types.MessageConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result types.MessageConnection `json:"messages"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return types.MessageConnection{}, err
	}

	return response.Result, nil
}
