// Code generated by gqlkit. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-chat/sdk/builder"
	"example-go-chat/sdk/fields"
	"example-go-chat/sdk/types"
)

// BillingCustomPlansBuilder builds a query for billingCustomPlans
//
// Embeds *builder.BaseBuilder for shared query-assembly + execution logic,
// and an op-kind marker (Query / Mutation) so the type only satisfies the
// matching batch.QueryBatchable / batch.MutationBatchable interface.
type BillingCustomPlansBuilder struct {
	*builder.BaseBuilder
	builder.QueryMarker
}

// Select configures which fields to return
func (b *BillingCustomPlansBuilder) Select(selector func(*fields.BillingPlanFields)) *BillingCustomPlansBuilder {
	selector(fields.NewBillingPlanFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *BillingCustomPlansBuilder) Execute(ctx context.Context) ([]*types.BillingPlan, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result []*types.BillingPlan `json:"billingCustomPlans"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return nil, err
	}

	return response.Result, nil
}
