// Code generated by gqlkit. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-chat/sdk/builder"
	"example-go-chat/sdk/fields"
	"example-go-chat/sdk/inputs"
	"example-go-chat/sdk/scalars"
	"example-go-chat/sdk/types"
)

// AiModels2Builder builds a query for aiModels2
//
// Embeds *builder.BaseBuilder for shared query-assembly + execution logic,
// and an op-kind marker (Query / Mutation) so the type only satisfies the
// matching batch.QueryBatchable / batch.MutationBatchable interface.
type AiModels2Builder struct {
	*builder.BaseBuilder
	builder.QueryMarker
}

// After sets the after argument
func (b *AiModels2Builder) After(v *scalars.Cursor) *AiModels2Builder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *AiModels2Builder) First(v *int) *AiModels2Builder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *AiModels2Builder) Before(v *scalars.Cursor) *AiModels2Builder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *AiModels2Builder) Last(v *int) *AiModels2Builder {
	b.SetArg("last", v, "Int")
	return b
}

// OrderBy sets the orderBy argument
func (b *AiModels2Builder) OrderBy(v []inputs.AiModelOrder) *AiModels2Builder {
	b.SetArg("orderBy", v, "[AiModelOrder!]")
	return b
}

// Where sets the where argument
func (b *AiModels2Builder) Where(v *inputs.AiModelWhereInput) *AiModels2Builder {
	b.SetArg("where", v, "AiModelWhereInput")
	return b
}

// Select configures which fields to return
func (b *AiModels2Builder) Select(selector func(*fields.AiModelConnectionFields)) *AiModels2Builder {
	selector(fields.NewAiModelConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *AiModels2Builder) Execute(ctx context.Context) (types.AiModelConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result types.AiModelConnection `json:"aiModels2"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return types.AiModelConnection{}, err
	}

	return response.Result, nil
}
