// Code generated by gqlkit. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-chat/sdk/builder"
	"example-go-chat/sdk/fields"
	"example-go-chat/sdk/scalars"
	"example-go-chat/sdk/types"
)

// BillingPlanWspacesBuilder builds a query for billingPlanWspaces
//
// Embeds *builder.BaseBuilder for shared query-assembly + execution logic,
// and an op-kind marker (Query / Mutation) so the type only satisfies the
// matching batch.QueryBatchable / batch.MutationBatchable interface.
type BillingPlanWspacesBuilder struct {
	*builder.BaseBuilder
	builder.QueryMarker
}

// After sets the after argument
func (b *BillingPlanWspacesBuilder) After(v *scalars.Cursor) *BillingPlanWspacesBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *BillingPlanWspacesBuilder) First(v *int) *BillingPlanWspacesBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *BillingPlanWspacesBuilder) Before(v *scalars.Cursor) *BillingPlanWspacesBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *BillingPlanWspacesBuilder) Last(v *int) *BillingPlanWspacesBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// Select configures which fields to return
func (b *BillingPlanWspacesBuilder) Select(selector func(*fields.BillingPlanWspaceConnectionFields)) *BillingPlanWspacesBuilder {
	selector(fields.NewBillingPlanWspaceConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *BillingPlanWspacesBuilder) Execute(ctx context.Context) (types.BillingPlanWspaceConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result types.BillingPlanWspaceConnection `json:"billingPlanWspaces"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return types.BillingPlanWspaceConnection{}, err
	}

	return response.Result, nil
}
