// Code generated by gqlkit. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-chat/sdk/builder"
	"example-go-chat/sdk/fields"
	"example-go-chat/sdk/inputs"
	"example-go-chat/sdk/scalars"
	"example-go-chat/sdk/types"
)

// ItemsBuilder builds a query for items
//
// Embeds *builder.BaseBuilder for shared query-assembly + execution logic,
// and an op-kind marker (Query / Mutation) so the type only satisfies the
// matching batch.QueryBatchable / batch.MutationBatchable interface.
type ItemsBuilder struct {
	*builder.BaseBuilder
	builder.QueryMarker
}

// After sets the after argument
func (b *ItemsBuilder) After(v *scalars.Cursor) *ItemsBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *ItemsBuilder) First(v *int) *ItemsBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *ItemsBuilder) Before(v *scalars.Cursor) *ItemsBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *ItemsBuilder) Last(v *int) *ItemsBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// OrderBy sets the orderBy argument
func (b *ItemsBuilder) OrderBy(v []inputs.ItemOrder) *ItemsBuilder {
	b.SetArg("orderBy", v, "[ItemOrder!]")
	return b
}

// Where sets the where argument
func (b *ItemsBuilder) Where(v *inputs.ItemWhereInput) *ItemsBuilder {
	b.SetArg("where", v, "ItemWhereInput")
	return b
}

// Select configures which fields to return
func (b *ItemsBuilder) Select(selector func(*fields.ItemConnectionFields)) *ItemsBuilder {
	selector(fields.NewItemConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *ItemsBuilder) Execute(ctx context.Context) (types.ItemConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result types.ItemConnection `json:"items"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return types.ItemConnection{}, err
	}

	return response.Result, nil
}
