// Code generated by gqlkit. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-chat/sdk/builder"
	"example-go-chat/sdk/fields"
	"example-go-chat/sdk/inputs"
	"example-go-chat/sdk/scalars"
	"example-go-chat/sdk/types"
)

// GuestsBuilder builds a query for guests
//
// Embeds *builder.BaseBuilder for shared query-assembly + execution logic,
// and an op-kind marker (Query / Mutation) so the type only satisfies the
// matching batch.QueryBatchable / batch.MutationBatchable interface.
type GuestsBuilder struct {
	*builder.BaseBuilder
	builder.QueryMarker
}

// After sets the after argument
func (b *GuestsBuilder) After(v *scalars.Cursor) *GuestsBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *GuestsBuilder) First(v *int) *GuestsBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *GuestsBuilder) Before(v *scalars.Cursor) *GuestsBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *GuestsBuilder) Last(v *int) *GuestsBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// OrderBy sets the orderBy argument
func (b *GuestsBuilder) OrderBy(v []inputs.GuestOrder) *GuestsBuilder {
	b.SetArg("orderBy", v, "[GuestOrder!]")
	return b
}

// Where sets the where argument
func (b *GuestsBuilder) Where(v *inputs.GuestWhereInput) *GuestsBuilder {
	b.SetArg("where", v, "GuestWhereInput")
	return b
}

// Select configures which fields to return
func (b *GuestsBuilder) Select(selector func(*fields.GuestConnectionFields)) *GuestsBuilder {
	selector(fields.NewGuestConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *GuestsBuilder) Execute(ctx context.Context) (types.GuestConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result types.GuestConnection `json:"guests"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return types.GuestConnection{}, err
	}

	return response.Result, nil
}
