// Code generated by gqlkit. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-chat/sdk/builder"
	"example-go-chat/sdk/fields"
	"example-go-chat/sdk/inputs"
	"example-go-chat/sdk/scalars"
	"example-go-chat/sdk/types"
)

// ChatbotToolsBuilder builds a query for chatbotTools
//
// Embeds *builder.BaseBuilder for shared query-assembly + execution logic,
// and an op-kind marker (Query / Mutation) so the type only satisfies the
// matching batch.QueryBatchable / batch.MutationBatchable interface.
type ChatbotToolsBuilder struct {
	*builder.BaseBuilder
	builder.QueryMarker
}

// After sets the after argument
func (b *ChatbotToolsBuilder) After(v *scalars.Cursor) *ChatbotToolsBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *ChatbotToolsBuilder) First(v *int) *ChatbotToolsBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *ChatbotToolsBuilder) Before(v *scalars.Cursor) *ChatbotToolsBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *ChatbotToolsBuilder) Last(v *int) *ChatbotToolsBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// OrderBy sets the orderBy argument
func (b *ChatbotToolsBuilder) OrderBy(v []inputs.ChatbotToolOrder) *ChatbotToolsBuilder {
	b.SetArg("orderBy", v, "[ChatbotToolOrder!]")
	return b
}

// Where sets the where argument
func (b *ChatbotToolsBuilder) Where(v *inputs.ChatbotToolWhereInput) *ChatbotToolsBuilder {
	b.SetArg("where", v, "ChatbotToolWhereInput")
	return b
}

// Select configures which fields to return
func (b *ChatbotToolsBuilder) Select(selector func(*fields.ChatbotToolConnectionFields)) *ChatbotToolsBuilder {
	selector(fields.NewChatbotToolConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *ChatbotToolsBuilder) Execute(ctx context.Context) (types.ChatbotToolConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result types.ChatbotToolConnection `json:"chatbotTools"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return types.ChatbotToolConnection{}, err
	}

	return response.Result, nil
}
