// Code generated by gqlkit. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-chat/sdk/builder"
	"example-go-chat/sdk/fields"
	"example-go-chat/sdk/types"
)

// WorkspaceDetailBuilder builds a query for workspaceDetail
//
// Embeds *builder.BaseBuilder for shared query-assembly + execution logic,
// and an op-kind marker (Query / Mutation) so the type only satisfies the
// matching batch.QueryBatchable / batch.MutationBatchable interface.
type WorkspaceDetailBuilder struct {
	*builder.BaseBuilder
	builder.QueryMarker
}

// Select configures which fields to return
func (b *WorkspaceDetailBuilder) Select(selector func(*fields.WorkspaceDetailFields)) *WorkspaceDetailBuilder {
	selector(fields.NewWorkspaceDetailFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *WorkspaceDetailBuilder) Execute(ctx context.Context) (*types.WorkspaceDetail, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result *types.WorkspaceDetail `json:"workspaceDetail"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return nil, err
	}

	return response.Result, nil
}
