// Code generated by gqlkit. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-chat/sdk/builder"
)

// ICanUserAccessWorkspaceBuilder builds a query for iCanUserAccessWorkspace
//
// Embeds *builder.BaseBuilder for shared query-assembly + execution logic,
// and an op-kind marker (Query / Mutation) so the type only satisfies the
// matching batch.QueryBatchable / batch.MutationBatchable interface.
type ICanUserAccessWorkspaceBuilder struct {
	*builder.BaseBuilder
	builder.QueryMarker
}

// ID sets the id argument
func (b *ICanUserAccessWorkspaceBuilder) ID(v string) *ICanUserAccessWorkspaceBuilder {
	b.SetArg("id", v, "String!")
	return b
}

// SbyteUserID sets the sbyteUserID argument
func (b *ICanUserAccessWorkspaceBuilder) SbyteUserID(v string) *ICanUserAccessWorkspaceBuilder {
	b.SetArg("sbyteUserID", v, "String!")
	return b
}

// Execute runs the query and returns the result
func (b *ICanUserAccessWorkspaceBuilder) Execute(ctx context.Context) (bool, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result bool `json:"iCanUserAccessWorkspace"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return false, err
	}

	return response.Result, nil
}
