// Code generated by gqlkit. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-chat/sdk/builder"
	"example-go-chat/sdk/fields"
	"example-go-chat/sdk/inputs"
	"example-go-chat/sdk/scalars"
	"example-go-chat/sdk/types"
)

// ItemGroupsBuilder builds a query for itemGroups
//
// Embeds *builder.BaseBuilder for shared query-assembly + execution logic,
// and an op-kind marker (Query / Mutation) so the type only satisfies the
// matching batch.QueryBatchable / batch.MutationBatchable interface.
type ItemGroupsBuilder struct {
	*builder.BaseBuilder
	builder.QueryMarker
}

// After sets the after argument
func (b *ItemGroupsBuilder) After(v *scalars.Cursor) *ItemGroupsBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *ItemGroupsBuilder) First(v *int) *ItemGroupsBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *ItemGroupsBuilder) Before(v *scalars.Cursor) *ItemGroupsBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *ItemGroupsBuilder) Last(v *int) *ItemGroupsBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// OrderBy sets the orderBy argument
func (b *ItemGroupsBuilder) OrderBy(v []inputs.ItemGroupOrder) *ItemGroupsBuilder {
	b.SetArg("orderBy", v, "[ItemGroupOrder!]")
	return b
}

// Where sets the where argument
func (b *ItemGroupsBuilder) Where(v *inputs.ItemGroupWhereInput) *ItemGroupsBuilder {
	b.SetArg("where", v, "ItemGroupWhereInput")
	return b
}

// Select configures which fields to return
func (b *ItemGroupsBuilder) Select(selector func(*fields.ItemGroupConnectionFields)) *ItemGroupsBuilder {
	selector(fields.NewItemGroupConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *ItemGroupsBuilder) Execute(ctx context.Context) (types.ItemGroupConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result types.ItemGroupConnection `json:"itemGroups"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return types.ItemGroupConnection{}, err
	}

	return response.Result, nil
}
