// Code generated by gqlkit. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-chat/sdk/builder"
	"example-go-chat/sdk/fields"
	"example-go-chat/sdk/types"
)

// ChatbotFoldersBuilder builds a query for chatbotFolders
//
// Embeds *builder.BaseBuilder for shared query-assembly + execution logic,
// and an op-kind marker (Query / Mutation) so the type only satisfies the
// matching batch.QueryBatchable / batch.MutationBatchable interface.
type ChatbotFoldersBuilder struct {
	*builder.BaseBuilder
	builder.QueryMarker
}

// ChatbotID sets the chatbotId argument
func (b *ChatbotFoldersBuilder) ChatbotID(v string) *ChatbotFoldersBuilder {
	b.SetArg("chatbotId", v, "String!")
	return b
}

// Select configures which fields to return
func (b *ChatbotFoldersBuilder) Select(selector func(*fields.FolderFields)) *ChatbotFoldersBuilder {
	selector(fields.NewFolderFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *ChatbotFoldersBuilder) Execute(ctx context.Context) ([]types.Folder, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result []types.Folder `json:"chatbotFolders"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return nil, err
	}

	return response.Result, nil
}
