// Code generated by gqlkit. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-chat/sdk/builder"
	"example-go-chat/sdk/fields"
	"example-go-chat/sdk/inputs"
	"example-go-chat/sdk/scalars"
	"example-go-chat/sdk/types"
)

// ItemGroupSourcesBuilder builds a query for itemGroupSources
//
// Embeds *builder.BaseBuilder for shared query-assembly + execution logic,
// and an op-kind marker (Query / Mutation) so the type only satisfies the
// matching batch.QueryBatchable / batch.MutationBatchable interface.
type ItemGroupSourcesBuilder struct {
	*builder.BaseBuilder
	builder.QueryMarker
}

// After sets the after argument
func (b *ItemGroupSourcesBuilder) After(v *scalars.Cursor) *ItemGroupSourcesBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *ItemGroupSourcesBuilder) First(v *int) *ItemGroupSourcesBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *ItemGroupSourcesBuilder) Before(v *scalars.Cursor) *ItemGroupSourcesBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *ItemGroupSourcesBuilder) Last(v *int) *ItemGroupSourcesBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// OrderBy sets the orderBy argument
func (b *ItemGroupSourcesBuilder) OrderBy(v []inputs.ItemGroupSourceOrder) *ItemGroupSourcesBuilder {
	b.SetArg("orderBy", v, "[ItemGroupSourceOrder!]")
	return b
}

// Where sets the where argument
func (b *ItemGroupSourcesBuilder) Where(v *inputs.ItemGroupSourceWhereInput) *ItemGroupSourcesBuilder {
	b.SetArg("where", v, "ItemGroupSourceWhereInput")
	return b
}

// Select configures which fields to return
func (b *ItemGroupSourcesBuilder) Select(selector func(*fields.ItemGroupSourceConnectionFields)) *ItemGroupSourcesBuilder {
	selector(fields.NewItemGroupSourceConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *ItemGroupSourcesBuilder) Execute(ctx context.Context) (types.ItemGroupSourceConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result types.ItemGroupSourceConnection `json:"itemGroupSources"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return types.ItemGroupSourceConnection{}, err
	}

	return response.Result, nil
}
