// Code generated by gqlkit. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-chat/sdk/builder"
	"example-go-chat/sdk/fields"
	"example-go-chat/sdk/inputs"
	"example-go-chat/sdk/scalars"
	"example-go-chat/sdk/types"
)

// MyChatbotUsersBuilder builds a query for myChatbotUsers
//
// Embeds *builder.BaseBuilder for shared query-assembly + execution logic,
// and an op-kind marker (Query / Mutation) so the type only satisfies the
// matching batch.QueryBatchable / batch.MutationBatchable interface.
type MyChatbotUsersBuilder struct {
	*builder.BaseBuilder
	builder.QueryMarker
}

// After sets the after argument
func (b *MyChatbotUsersBuilder) After(v *scalars.Cursor) *MyChatbotUsersBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *MyChatbotUsersBuilder) First(v *int) *MyChatbotUsersBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *MyChatbotUsersBuilder) Before(v *scalars.Cursor) *MyChatbotUsersBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *MyChatbotUsersBuilder) Last(v *int) *MyChatbotUsersBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// OrderBy sets the orderBy argument
func (b *MyChatbotUsersBuilder) OrderBy(v []inputs.ChatbotUserOrder) *MyChatbotUsersBuilder {
	b.SetArg("orderBy", v, "[ChatbotUserOrder!]")
	return b
}

// Where sets the where argument
func (b *MyChatbotUsersBuilder) Where(v *inputs.ChatbotUserWhereInput) *MyChatbotUsersBuilder {
	b.SetArg("where", v, "ChatbotUserWhereInput")
	return b
}

// Select configures which fields to return
func (b *MyChatbotUsersBuilder) Select(selector func(*fields.ChatbotUserConnectionFields)) *MyChatbotUsersBuilder {
	selector(fields.NewChatbotUserConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *MyChatbotUsersBuilder) Execute(ctx context.Context) (types.ChatbotUserConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result types.ChatbotUserConnection `json:"myChatbotUsers"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return types.ChatbotUserConnection{}, err
	}

	return response.Result, nil
}
