// Code generated by gqlkit. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-chat/sdk/builder"
	"example-go-chat/sdk/fields"
	"example-go-chat/sdk/inputs"
	"example-go-chat/sdk/types"
)

// IChatbotBuilder builds a query for iChatbot
//
// Embeds *builder.BaseBuilder for shared query-assembly + execution logic,
// and an op-kind marker (Query / Mutation) so the type only satisfies the
// matching batch.QueryBatchable / batch.MutationBatchable interface.
type IChatbotBuilder struct {
	*builder.BaseBuilder
	builder.QueryMarker
}

// ID sets the id argument
func (b *IChatbotBuilder) ID(v string) *IChatbotBuilder {
	b.SetArg("id", v, "String!")
	return b
}

// Input sets the input argument
func (b *IChatbotBuilder) Input(v *inputs.IChatbotGetInput) *IChatbotBuilder {
	b.SetArg("input", v, "IChatbotGetInput")
	return b
}

// Select configures which fields to return
func (b *IChatbotBuilder) Select(selector func(*fields.ChatbotFields)) *IChatbotBuilder {
	selector(fields.NewChatbotFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *IChatbotBuilder) Execute(ctx context.Context) (types.Chatbot, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result types.Chatbot `json:"iChatbot"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return types.Chatbot{}, err
	}

	return response.Result, nil
}
