// Code generated by gqlkit. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-chat/sdk/builder"
	"example-go-chat/sdk/fields"
	"example-go-chat/sdk/inputs"
	"example-go-chat/sdk/scalars"
	"example-go-chat/sdk/types"
)

// FoldersBuilder builds a query for folders
//
// Embeds *builder.BaseBuilder for shared query-assembly + execution logic,
// and an op-kind marker (Query / Mutation) so the type only satisfies the
// matching batch.QueryBatchable / batch.MutationBatchable interface.
type FoldersBuilder struct {
	*builder.BaseBuilder
	builder.QueryMarker
}

// After sets the after argument
func (b *FoldersBuilder) After(v *scalars.Cursor) *FoldersBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *FoldersBuilder) First(v *int) *FoldersBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *FoldersBuilder) Before(v *scalars.Cursor) *FoldersBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *FoldersBuilder) Last(v *int) *FoldersBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// OrderBy sets the orderBy argument
func (b *FoldersBuilder) OrderBy(v []inputs.FolderOrder) *FoldersBuilder {
	b.SetArg("orderBy", v, "[FolderOrder!]")
	return b
}

// Where sets the where argument
func (b *FoldersBuilder) Where(v *inputs.FolderWhereInput) *FoldersBuilder {
	b.SetArg("where", v, "FolderWhereInput")
	return b
}

// Select configures which fields to return
func (b *FoldersBuilder) Select(selector func(*fields.FolderConnectionFields)) *FoldersBuilder {
	selector(fields.NewFolderConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *FoldersBuilder) Execute(ctx context.Context) (types.FolderConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result types.FolderConnection `json:"folders"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return types.FolderConnection{}, err
	}

	return response.Result, nil
}
