// Code generated by gqlkit. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-chat/sdk/builder"
	"example-go-chat/sdk/fields"
	"example-go-chat/sdk/inputs"
	"example-go-chat/sdk/scalars"
	"example-go-chat/sdk/types"
)

// ChannelsBuilder builds a query for channels
//
// Embeds *builder.BaseBuilder for shared query-assembly + execution logic,
// and an op-kind marker (Query / Mutation) so the type only satisfies the
// matching batch.QueryBatchable / batch.MutationBatchable interface.
type ChannelsBuilder struct {
	*builder.BaseBuilder
	builder.QueryMarker
}

// After sets the after argument
func (b *ChannelsBuilder) After(v *scalars.Cursor) *ChannelsBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *ChannelsBuilder) First(v *int) *ChannelsBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *ChannelsBuilder) Before(v *scalars.Cursor) *ChannelsBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *ChannelsBuilder) Last(v *int) *ChannelsBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// OrderBy sets the orderBy argument
func (b *ChannelsBuilder) OrderBy(v []inputs.ChannelOrder) *ChannelsBuilder {
	b.SetArg("orderBy", v, "[ChannelOrder!]")
	return b
}

// Where sets the where argument
func (b *ChannelsBuilder) Where(v *inputs.ChannelWhereInput) *ChannelsBuilder {
	b.SetArg("where", v, "ChannelWhereInput")
	return b
}

// Select configures which fields to return
func (b *ChannelsBuilder) Select(selector func(*fields.ChannelConnectionFields)) *ChannelsBuilder {
	selector(fields.NewChannelConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *ChannelsBuilder) Execute(ctx context.Context) (types.ChannelConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result types.ChannelConnection `json:"channels"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return types.ChannelConnection{}, err
	}

	return response.Result, nil
}
