// Code generated by gqlkit. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-chat/sdk/builder"
	"example-go-chat/sdk/fields"
	"example-go-chat/sdk/inputs"
	"example-go-chat/sdk/scalars"
	"example-go-chat/sdk/types"
)

// CredentialsBuilder builds a query for credentials
//
// Embeds *builder.BaseBuilder for shared query-assembly + execution logic,
// and an op-kind marker (Query / Mutation) so the type only satisfies the
// matching batch.QueryBatchable / batch.MutationBatchable interface.
type CredentialsBuilder struct {
	*builder.BaseBuilder
	builder.QueryMarker
}

// After sets the after argument
func (b *CredentialsBuilder) After(v *scalars.Cursor) *CredentialsBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *CredentialsBuilder) First(v *int) *CredentialsBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *CredentialsBuilder) Before(v *scalars.Cursor) *CredentialsBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *CredentialsBuilder) Last(v *int) *CredentialsBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// OrderBy sets the orderBy argument
func (b *CredentialsBuilder) OrderBy(v []inputs.CredentialOrder) *CredentialsBuilder {
	b.SetArg("orderBy", v, "[CredentialOrder!]")
	return b
}

// Where sets the where argument
func (b *CredentialsBuilder) Where(v *inputs.CredentialWhereInput) *CredentialsBuilder {
	b.SetArg("where", v, "CredentialWhereInput")
	return b
}

// Select configures which fields to return
func (b *CredentialsBuilder) Select(selector func(*fields.CredentialConnectionFields)) *CredentialsBuilder {
	selector(fields.NewCredentialConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *CredentialsBuilder) Execute(ctx context.Context) (types.CredentialConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result types.CredentialConnection `json:"credentials"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return types.CredentialConnection{}, err
	}

	return response.Result, nil
}
