// Code generated by gqlkit. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-chat/sdk/builder"
	"example-go-chat/sdk/fields"
	"example-go-chat/sdk/types"
)

// IChannelBuilder builds a query for iChannel
//
// Embeds *builder.BaseBuilder for shared query-assembly + execution logic,
// and an op-kind marker (Query / Mutation) so the type only satisfies the
// matching batch.QueryBatchable / batch.MutationBatchable interface.
type IChannelBuilder struct {
	*builder.BaseBuilder
	builder.QueryMarker
}

// ID sets the id argument
func (b *IChannelBuilder) ID(v string) *IChannelBuilder {
	b.SetArg("id", v, "String!")
	return b
}

// UserIds sets the userIds argument
func (b *IChannelBuilder) UserIds(v []string) *IChannelBuilder {
	b.SetArg("userIds", v, "[String!]")
	return b
}

// Select configures which fields to return
func (b *IChannelBuilder) Select(selector func(*fields.ChannelFields)) *IChannelBuilder {
	selector(fields.NewChannelFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *IChannelBuilder) Execute(ctx context.Context) (types.Channel, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result types.Channel `json:"iChannel"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return types.Channel{}, err
	}

	return response.Result, nil
}
