// Code generated by gqlkit. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-chat/sdk/builder"
	"example-go-chat/sdk/fields"
	"example-go-chat/sdk/inputs"
	"example-go-chat/sdk/scalars"
	"example-go-chat/sdk/types"
)

// ChannelUsersBuilder builds a query for channelUsers
//
// Embeds *builder.BaseBuilder for shared query-assembly + execution logic,
// and an op-kind marker (Query / Mutation) so the type only satisfies the
// matching batch.QueryBatchable / batch.MutationBatchable interface.
type ChannelUsersBuilder struct {
	*builder.BaseBuilder
	builder.QueryMarker
}

// After sets the after argument
func (b *ChannelUsersBuilder) After(v *scalars.Cursor) *ChannelUsersBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *ChannelUsersBuilder) First(v *int) *ChannelUsersBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *ChannelUsersBuilder) Before(v *scalars.Cursor) *ChannelUsersBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *ChannelUsersBuilder) Last(v *int) *ChannelUsersBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// OrderBy sets the orderBy argument
func (b *ChannelUsersBuilder) OrderBy(v []inputs.ChannelUserOrder) *ChannelUsersBuilder {
	b.SetArg("orderBy", v, "[ChannelUserOrder!]")
	return b
}

// Where sets the where argument
func (b *ChannelUsersBuilder) Where(v *inputs.ChannelUserWhereInput) *ChannelUsersBuilder {
	b.SetArg("where", v, "ChannelUserWhereInput")
	return b
}

// Select configures which fields to return
func (b *ChannelUsersBuilder) Select(selector func(*fields.ChannelUserConnectionFields)) *ChannelUsersBuilder {
	selector(fields.NewChannelUserConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *ChannelUsersBuilder) Execute(ctx context.Context) (types.ChannelUserConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result types.ChannelUserConnection `json:"channelUsers"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return types.ChannelUserConnection{}, err
	}

	return response.Result, nil
}
