// Code generated by gqlkit. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-chat/sdk/builder"
	"example-go-chat/sdk/fields"
	"example-go-chat/sdk/inputs"
	"example-go-chat/sdk/scalars"
	"example-go-chat/sdk/types"
)

// UsersBuilder builds a query for users
//
// Embeds *builder.BaseBuilder for shared query-assembly + execution logic,
// and an op-kind marker (Query / Mutation) so the type only satisfies the
// matching batch.QueryBatchable / batch.MutationBatchable interface.
type UsersBuilder struct {
	*builder.BaseBuilder
	builder.QueryMarker
}

// After sets the after argument
func (b *UsersBuilder) After(v *scalars.Cursor) *UsersBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *UsersBuilder) First(v *int) *UsersBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *UsersBuilder) Before(v *scalars.Cursor) *UsersBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *UsersBuilder) Last(v *int) *UsersBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// OrderBy sets the orderBy argument
func (b *UsersBuilder) OrderBy(v []inputs.UserOrder) *UsersBuilder {
	b.SetArg("orderBy", v, "[UserOrder!]")
	return b
}

// Where sets the where argument
func (b *UsersBuilder) Where(v *inputs.UserWhereInput) *UsersBuilder {
	b.SetArg("where", v, "UserWhereInput")
	return b
}

// Select configures which fields to return
func (b *UsersBuilder) Select(selector func(*fields.UserConnectionFields)) *UsersBuilder {
	selector(fields.NewUserConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *UsersBuilder) Execute(ctx context.Context) (types.UserConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result types.UserConnection `json:"users"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return types.UserConnection{}, err
	}

	return response.Result, nil
}
