// Code generated by gqlkit. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-chat/sdk/builder"
	"example-go-chat/sdk/fields"
	"example-go-chat/sdk/inputs"
	"example-go-chat/sdk/scalars"
	"example-go-chat/sdk/types"
)

// AiModelsBuilder builds a query for aiModels
//
// Embeds *builder.BaseBuilder for shared query-assembly + execution logic,
// and an op-kind marker (Query / Mutation) so the type only satisfies the
// matching batch.QueryBatchable / batch.MutationBatchable interface.
type AiModelsBuilder struct {
	*builder.BaseBuilder
	builder.QueryMarker
}

// After sets the after argument
func (b *AiModelsBuilder) After(v *scalars.Cursor) *AiModelsBuilder {
	b.SetArg("after", v, "Cursor")
	return b
}

// First sets the first argument
func (b *AiModelsBuilder) First(v *int) *AiModelsBuilder {
	b.SetArg("first", v, "Int")
	return b
}

// Before sets the before argument
func (b *AiModelsBuilder) Before(v *scalars.Cursor) *AiModelsBuilder {
	b.SetArg("before", v, "Cursor")
	return b
}

// Last sets the last argument
func (b *AiModelsBuilder) Last(v *int) *AiModelsBuilder {
	b.SetArg("last", v, "Int")
	return b
}

// OrderBy sets the orderBy argument
func (b *AiModelsBuilder) OrderBy(v []inputs.AiModelOrder) *AiModelsBuilder {
	b.SetArg("orderBy", v, "[AiModelOrder!]")
	return b
}

// Where sets the where argument
func (b *AiModelsBuilder) Where(v *inputs.AiModelWhereInput) *AiModelsBuilder {
	b.SetArg("where", v, "AiModelWhereInput")
	return b
}

// Select configures which fields to return
func (b *AiModelsBuilder) Select(selector func(*fields.AiModelConnectionFields)) *AiModelsBuilder {
	selector(fields.NewAiModelConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *AiModelsBuilder) Execute(ctx context.Context) (types.AiModelConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result types.AiModelConnection `json:"aiModels"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return types.AiModelConnection{}, err
	}

	return response.Result, nil
}
