// Code generated by gqlkit. DO NOT EDIT.

import { BaseBuilder, GraphQLClient } from "../builder";

/** EchoBuilder builds a query for echo */
export class EchoBuilder {
  private builder: BaseBuilder;

  constructor(client: GraphQLClient) {
    this.builder = new BaseBuilder(client, "query", "Echo", "echo");
  }

  /** Sets the message argument */
  message(v: string): this {
    this.builder.setArg("message", v, "String!");
    return this;
  }

  /** Execute runs the query and returns the result */
  async execute(): Promise<string> {
    const query = this.builder.buildQuery();
    const variables = this.builder.getVariables();

    const response = await this.builder
      .getClient()
      .execute<{ echo: string }>(query, variables);

    return response.echo;
  }

  /** ExecuteRaw runs the query and returns the raw response */
  async executeRaw(): Promise<Record<string, unknown>> {
    return await this.builder.executeRaw();
  }

  /** Internal — exposes this operation as a fragment for batch() */
  getOpFragment(alias: string) {
    return this.builder.getOpFragment(alias);
  }
}
