// Code generated by gqlkit. DO NOT EDIT.

import { BaseBuilder, GraphQLClient } from "../builder";

/** SearchBuilder builds a query for search */
export class SearchBuilder {
  private builder: BaseBuilder;

  constructor(client: GraphQLClient) {
    this.builder = new BaseBuilder(client, "query", "Search", "search");
  }

  /** Sets the term argument */
  term(v: string): this {
    this.builder.setArg("term", v, "String!");
    return this;
  }

  /** Execute runs the query and returns the result */
  async execute(): Promise<any[]> {
    const query = this.builder.buildQuery();
    const variables = this.builder.getVariables();

    const response = await this.builder
      .getClient()
      .execute<{ search: any[] }>(query, variables);

    return response.search;
  }

  /** ExecuteRaw runs the query and returns the raw response */
  async executeRaw(): Promise<Record<string, unknown>> {
    return await this.builder.executeRaw();
  }

  /** Internal — exposes this operation as a fragment for batch() */
  getOpFragment(alias: string) {
    return this.builder.getOpFragment(alias);
  }
}
