// Code generated by gqlkit. DO NOT EDIT.

import { BaseBuilder, GraphQLClient } from "../builder";

/** SumBuilder builds a query for sum */
export class SumBuilder {
  private builder: BaseBuilder;

  constructor(client: GraphQLClient) {
    this.builder = new BaseBuilder(client, "query", "Sum", "sum");
  }

  /** Sets the a argument */
  a(v: number): this {
    this.builder.setArg("a", v, "Int!");
    return this;
  }

  /** Sets the b argument */
  b(v: number): this {
    this.builder.setArg("b", v, "Int!");
    return this;
  }

  /** Execute runs the query and returns the result */
  async execute(): Promise<number> {
    const query = this.builder.buildQuery();
    const variables = this.builder.getVariables();

    const response = await this.builder
      .getClient()
      .execute<{ sum: number }>(query, variables);

    return response.sum;
  }

  /** ExecuteRaw runs the query and returns the raw response */
  async executeRaw(): Promise<Record<string, unknown>> {
    return await this.builder.executeRaw();
  }

  /** Internal — exposes this operation as a fragment for batch() */
  getOpFragment(alias: string) {
    return this.builder.getOpFragment(alias);
  }
}
