// Code generated by gqlkit. DO NOT EDIT.

import { BaseBuilder, GraphQLClient } from "../builder";
import { TodoFields } from "../fields";
import type { Todo } from "../types";

/** TodoBuilder builds a query for todo */
export class TodoBuilder<TResult = Todo | null> {
  private builder: BaseBuilder;

  constructor(client: GraphQLClient) {
    this.builder = new BaseBuilder(client, "query", "Todo", "todo");
  }

  /** Sets the id argument */
  id(v: string): this {
    this.builder.setArg("id", v, "ID!");
    return this;
  }

  /** Configures which fields to return */
  select<T extends object>(selector: (f: TodoFields) => TodoFields<T>): TodoBuilder<T | null> {
    selector(new TodoFields(this.builder.getSelection()));
    return this as any;
  }

  /** Execute runs the query and returns the result */
  async execute(): Promise<TResult> {
    const query = this.builder.buildQuery();
    const variables = this.builder.getVariables();

    const response = await this.builder
      .getClient()
      .execute<{ todo: TResult }>(query, variables);

    return response.todo;
  }

  /** ExecuteRaw runs the query and returns the raw response */
  async executeRaw(): Promise<Record<string, unknown>> {
    return await this.builder.executeRaw();
  }

  /** Internal — exposes this operation as a fragment for batch() */
  getOpFragment(alias: string) {
    return this.builder.getOpFragment(alias);
  }
}
