// Code generated by gqlkit. DO NOT EDIT.

import { BaseBuilder, GraphQLClient } from "../builder";
import { TodoConnectionFields } from "../fields";
import type { TodoConnection } from "../types";
import type { PaginationInput, TodoFilter } from "../inputs";

/** TodosConnectionBuilder builds a query for todosConnection */
export class TodosConnectionBuilder<TResult = TodoConnection> {
  private builder: BaseBuilder;

  constructor(client: GraphQLClient) {
    this.builder = new BaseBuilder(client, "query", "TodosConnection", "todosConnection");
  }

  /** Sets the filter argument */
  filter(v: TodoFilter): this {
    this.builder.setArg("filter", v, "TodoFilter");
    return this;
  }

  /** Sets the pagination argument */
  pagination(v: PaginationInput): this {
    this.builder.setArg("pagination", v, "PaginationInput");
    return this;
  }

  /** Configures which fields to return */
  select<T extends object>(selector: (f: TodoConnectionFields) => TodoConnectionFields<T>): TodosConnectionBuilder<T> {
    selector(new TodoConnectionFields(this.builder.getSelection()));
    return this as any;
  }

  /** Execute runs the query and returns the result */
  async execute(): Promise<TResult> {
    const query = this.builder.buildQuery();
    const variables = this.builder.getVariables();

    const response = await this.builder
      .getClient()
      .execute<{ todosConnection: TResult }>(query, variables);

    return response.todosConnection;
  }

  /** ExecuteRaw runs the query and returns the raw response */
  async executeRaw(): Promise<Record<string, unknown>> {
    return await this.builder.executeRaw();
  }

  /** Internal — exposes this operation as a fragment for batch() */
  getOpFragment(alias: string) {
    return this.builder.getOpFragment(alias);
  }
}
