// Code generated by gqlkit. DO NOT EDIT.

import { BaseBuilder, GraphQLClient } from "../builder";
import { TodoFields } from "../fields";
import type { Todo } from "../types";
import type { PaginationInput, TodoFilter } from "../inputs";

/** TodosBuilder builds a query for todos */
export class TodosBuilder<TResult = Todo[]> {
  private builder: BaseBuilder;

  constructor(client: GraphQLClient) {
    this.builder = new BaseBuilder(client, "query", "Todos", "todos");
  }

  /** Sets the filter argument */
  filter(v: TodoFilter): this {
    this.builder.setArg("filter", v, "TodoFilter");
    return this;
  }

  /** Sets the pagination argument */
  pagination(v: PaginationInput): this {
    this.builder.setArg("pagination", v, "PaginationInput");
    return this;
  }

  /** Configures which fields to return */
  select<T extends object>(selector: (f: TodoFields) => TodoFields<T>): TodosBuilder<T[]> {
    selector(new TodoFields(this.builder.getSelection()));
    return this as any;
  }

  /** Execute runs the query and returns the result */
  async execute(): Promise<TResult> {
    const query = this.builder.buildQuery();
    const variables = this.builder.getVariables();

    const response = await this.builder
      .getClient()
      .execute<{ todos: TResult }>(query, variables);

    return response.todos;
  }

  /** ExecuteRaw runs the query and returns the raw response */
  async executeRaw(): Promise<Record<string, unknown>> {
    return await this.builder.executeRaw();
  }

  /** Internal — exposes this operation as a fragment for batch() */
  getOpFragment(alias: string) {
    return this.builder.getOpFragment(alias);
  }
}
