// Code generated by gqlkit. DO NOT EDIT.

import { BaseBuilder, GraphQLClient } from "../builder";
import { UserFields } from "../fields";
import type { User } from "../types";

/** UsersBuilder builds a query for users */
export class UsersBuilder<TResult = User[]> {
  private builder: BaseBuilder;

  constructor(client: GraphQLClient) {
    this.builder = new BaseBuilder(client, "query", "Users", "users");
  }

  /** Configures which fields to return */
  select<T extends object>(selector: (f: UserFields) => UserFields<T>): UsersBuilder<T[]> {
    selector(new UserFields(this.builder.getSelection()));
    return this as any;
  }

  /** Execute runs the query and returns the result */
  async execute(): Promise<TResult> {
    const query = this.builder.buildQuery();
    const variables = this.builder.getVariables();

    const response = await this.builder
      .getClient()
      .execute<{ users: TResult }>(query, variables);

    return response.users;
  }

  /** ExecuteRaw runs the query and returns the raw response */
  async executeRaw(): Promise<Record<string, unknown>> {
    return await this.builder.executeRaw();
  }

  /** Internal — exposes this operation as a fragment for batch() */
  getOpFragment(alias: string) {
    return this.builder.getOpFragment(alias);
  }
}
