package clientgen

import (
	"bytes"
	"fmt"
	"github.com/khanakia/gqlkit/gqlkit/pkg/util"
	"sort"
	"strings"

	"github.com/vektah/gqlparser/v2/ast"
)


// FieldSelectorData is the template data for generating a type-safe field
// selector struct. Each GraphQL object type gets its own selector that wraps
// builder.FieldSelection with typed methods for each field.
type FieldSelectorData struct {
	BuilderPkgImport string // full import path, e.g. "github.com/khanakia/gqlkit/gqlkit/pkg/builder"
	BuilderPkgName   string // package identifier in code, e.g. "builder"
	TypeName         string
	SelectorName     string
	Fields           []FieldSelField
}

// FieldSelField describes one field on a field selector. Scalar fields produce
// simple AddField calls; object fields produce nested selector callbacks.
type FieldSelField struct {
	FieldName      string
	MethodName     string
	IsObject       bool
	NestedSelector string
}

// getBaseTypeName returns the named type after unwrapping List and NonNull
func getBaseTypeName(t *ast.Type) string {
	if t == nil {
		return ""
	}
	if t.Elem != nil {
		return getBaseTypeName(t.Elem)
	}
	return t.NamedType
}

// isObjectType returns true if the type is an Object or Interface (needs nested selection)
func isObjectType(schema *ast.Schema, t *ast.Type) bool {
	name := getBaseTypeName(t)
	if name == "" {
		return false
	}
	def := schema.Types[name]
	if def == nil {
		return false
	}
	return def.Kind == ast.Object || def.Kind == ast.Interface
}

// getSortedObjectTypeNames returns schema object type names (excluding builtin and roots), sorted
func (g *Generator) getSortedObjectTypeNames() []string {
	var names []string
	for name, def := range g.schema.Types {
		if def.BuiltIn || strings.HasPrefix(name, "__") {
			continue
		}
		if def.Kind != ast.Object && def.Kind != ast.Interface {
			continue
		}
		// Conventional roots have no data struct (see generateTypes), so no
		// field selector. Non-conventional roots (QueryRoot) DO get one — other
		// types can select into them via an object field.
		if name == "Query" || name == "Mutation" || name == "Subscription" {
			continue
		}
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

// buildFieldSelectorData builds template data for one object type's field selector
func (g *Generator) buildFieldSelectorData(def *ast.Definition) FieldSelectorData {
	data := FieldSelectorData{
		TypeName:     def.Name,
		SelectorName: exportName(def.Name) + "Fields",
		Fields:       make([]FieldSelField, 0, len(def.Fields)),
	}

	// Builder package: prefer configured SDK package (e.g. gqlkit/sdk) then /builder.
	rootPkg := strings.TrimSuffix(g.config.Package, "/")
	if rootPkg != "" {
		data.BuilderPkgImport = rootPkg + "/builder"
	}
	data.BuilderPkgName = "builder"
	if idx := strings.LastIndex(data.BuilderPkgImport, "/"); idx >= 0 && idx < len(data.BuilderPkgImport)-1 {
		data.BuilderPkgName = data.BuilderPkgImport[idx+1:]
	}

	for _, field := range def.Fields {
		if skipGenField(field.Name) {
			continue
		}
		baseName := getBaseTypeName(field.Type)
		isObj := isObjectType(g.schema, field.Type)

		f := FieldSelField{
			FieldName:  field.Name,
			MethodName: util.ToPascalCase(field.Name),
			IsObject:   isObj,
		}
		if isObj {
			f.NestedSelector = exportName(baseName) + "Fields"
		}
		data.Fields = append(data.Fields, f)
	}

	return data
}

// generateFieldSelectionFiles generates one Go file per object type in the
// fields/ directory. Each file contains a type-safe field selector struct that
// wraps builder.FieldSelection with methods for each field of that type.
func (g *Generator) generateFieldSelectionFiles() error {
	names := g.getSortedObjectTypeNames()
	for _, name := range names {
		def := g.schema.Types[name]
		if def == nil {
			continue
		}
		data := g.buildFieldSelectorData(def)
		var buf bytes.Buffer
		if err := g.templates.ExecuteTemplate(&buf, "field_selector", data); err != nil {
			return fmt.Errorf("field selector template for %s: %w", name, err)
		}
		filename := fmt.Sprintf("fields/field_%s.go", util.ToSnakeCase(name))
		content := "// Code generated by gqlkit. DO NOT EDIT.\n\npackage fields\n\nimport (\n\t\"" + data.BuilderPkgImport + "\"\n)\n\n" + buf.String()
		if err := g.writer.WriteFile(filename, content); err != nil {
			return fmt.Errorf("write %s: %w", filename, err)
		}
	}
	return nil
}
