// Code generated by gqlkit. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-mockapi/sdk/builder"
	"example-go-mockapi/sdk/fields"
	"example-go-mockapi/sdk/types"
)

// UsersBuilder builds a query for users
//
// Embeds *builder.BaseBuilder for shared query-assembly + execution logic,
// and an op-kind marker (Query / Mutation) so the type only satisfies the
// matching batch.QueryBatchable / batch.MutationBatchable interface.
type UsersBuilder struct {
	*builder.BaseBuilder
	builder.QueryMarker
}

// Select configures which fields to return
func (b *UsersBuilder) Select(selector func(*fields.UserFields)) *UsersBuilder {
	selector(fields.NewUserFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *UsersBuilder) Execute(ctx context.Context) ([]types.User, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result []types.User `json:"users"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return nil, err
	}

	return response.Result, nil
}
