// Code generated by gqlkit. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-mockapi/sdk/builder"
	"example-go-mockapi/sdk/fields"
	"example-go-mockapi/sdk/types"
)

// TodoBuilder builds a query for todo
type TodoBuilder struct {
	*builder.BaseBuilder
	builder.QueryMarker
}

// ID sets the id argument
func (b *TodoBuilder) ID(v string) *TodoBuilder {
	b.SetArg("id", v, "ID!")
	return b
}

// Select configures which fields to return
func (b *TodoBuilder) Select(selector func(*fields.TodoFields)) *TodoBuilder {
	selector(fields.NewTodoFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *TodoBuilder) Execute(ctx context.Context) (*types.Todo, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result *types.Todo `json:"todo"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return nil, err
	}

	return response.Result, nil
}
