// Code generated by gqlkit. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-mockapi/sdk/builder"
)

// PingBuilder builds a query for ping
type PingBuilder struct {
	*builder.BaseBuilder
	builder.QueryMarker
}

// Execute runs the query and returns the result
func (b *PingBuilder) Execute(ctx context.Context) (string, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result string `json:"ping"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return "", err
	}

	return response.Result, nil
}
