// Code generated by gqlkit. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-mockapi/sdk/builder"
)

// SearchBuilder builds a query for search
//
// Embeds *builder.BaseBuilder for shared query-assembly + execution logic,
// and an op-kind marker (Query / Mutation) so the type only satisfies the
// matching batch.QueryBatchable / batch.MutationBatchable interface.
type SearchBuilder struct {
	*builder.BaseBuilder
	builder.QueryMarker
}

// Term sets the term argument
func (b *SearchBuilder) Term(v string) *SearchBuilder {
	b.SetArg("term", v, "String!")
	return b
}

// Execute runs the query and returns the result
func (b *SearchBuilder) Execute(ctx context.Context) ([]interface{}, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result []interface{} `json:"search"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return nil, err
	}

	return response.Result, nil
}
