// Code generated by gqlkit. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-mockapi/sdk/builder"
)

// EchoBuilder builds a query for echo
type EchoBuilder struct {
	*builder.BaseBuilder
	builder.QueryMarker
}

// Message sets the message argument
func (b *EchoBuilder) Message(v string) *EchoBuilder {
	b.SetArg("message", v, "String!")
	return b
}

// Execute runs the query and returns the result
func (b *EchoBuilder) Execute(ctx context.Context) (string, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result string `json:"echo"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return "", err
	}

	return response.Result, nil
}
