// Code generated by gqlkit. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-mockapi/sdk/builder"
	"example-go-mockapi/sdk/fields"
	"example-go-mockapi/sdk/types"
)

// UserBuilder builds a query for user
//
// Embeds *builder.BaseBuilder for shared query-assembly + execution logic,
// and an op-kind marker (Query / Mutation) so the type only satisfies the
// matching batch.QueryBatchable / batch.MutationBatchable interface.
type UserBuilder struct {
	*builder.BaseBuilder
	builder.QueryMarker
}

// ID sets the id argument
func (b *UserBuilder) ID(v string) *UserBuilder {
	b.SetArg("id", v, "ID!")
	return b
}

// Select configures which fields to return
func (b *UserBuilder) Select(selector func(*fields.UserFields)) *UserBuilder {
	selector(fields.NewUserFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *UserBuilder) Execute(ctx context.Context) (*types.User, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result *types.User `json:"user"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return nil, err
	}

	return response.Result, nil
}
