// Code generated by gqlkit. DO NOT EDIT.

package queries

import (
	"context"
	"encoding/json"
	"example-go-mockapi/sdk/builder"
)

// ServerInfoBuilder builds a query for serverInfo
type ServerInfoBuilder struct {
	*builder.BaseBuilder
	builder.QueryMarker
}

// Execute runs the query and returns the result
func (b *ServerInfoBuilder) Execute(ctx context.Context) (json.RawMessage, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result json.RawMessage `json:"serverInfo"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return json.RawMessage{}, err
	}

	return response.Result, nil
}
