// Code generated by gqlkit. DO NOT EDIT.

package queries

import (
	"context"
	"example-go-mockapi/sdk/builder"
	"example-go-mockapi/sdk/fields"
	"example-go-mockapi/sdk/inputs"
	"example-go-mockapi/sdk/types"
)

// TodosConnectionBuilder builds a query for todosConnection
type TodosConnectionBuilder struct {
	*builder.BaseBuilder
	builder.QueryMarker
}

// Filter sets the filter argument
func (b *TodosConnectionBuilder) Filter(v *inputs.TodoFilter) *TodosConnectionBuilder {
	b.SetArg("filter", v, "TodoFilter")
	return b
}

// Pagination sets the pagination argument
func (b *TodosConnectionBuilder) Pagination(v *inputs.PaginationInput) *TodosConnectionBuilder {
	b.SetArg("pagination", v, "PaginationInput")
	return b
}

// Select configures which fields to return
func (b *TodosConnectionBuilder) Select(selector func(*fields.TodoConnectionFields)) *TodosConnectionBuilder {
	selector(fields.NewTodoConnectionFields(b.GetSelection()))
	return b
}

// Execute runs the query and returns the result
func (b *TodosConnectionBuilder) Execute(ctx context.Context) (types.TodoConnection, error) {
	query := b.BuildQuery()
	variables := b.GetVariables()

	var response struct {
		Result types.TodoConnection `json:"todosConnection"`
	}

	if err := b.GetClient().Execute(ctx, query, variables, &response); err != nil {
		return types.TodoConnection{}, err
	}

	return response.Result, nil
}
