// Code generated by ent, DO NOT EDIT.

package scalars

import (
	"encoding/json"

	"time"
)

type (
	Boolean = bool

	Cursor = string

	DateTime = time.Time

	Float = float64

	ID = string

	Int = int

	JSON = json.RawMessage

	Metadata = any

	String = string
)
